version: '3.9'
services:
    data-narrator-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:80'
    story-backend:
        build:
            context: ./story-backend
        ports:
            - "4000:80"
            - "4443:443"
