version: '3.9'
services:
    data-narrator-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        ports:
            - '3000:80'
    story-backend:

        build:
            context: ./story-backend
        network_mode: "host"
        ports:
            - "4000:80"
            - "4443:443"
        dns:
            - 8.8.8.8  # Google's DNS server
            - 8.8.4.4  # Google's DNS server
