services:
    data-narrator-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:80'
        volumes:
            - /opt/psa/var/modules/letsencrypt/etc/live/_plesk_domain/fullchain.pem:/etc/ssl/certs/mycert.pem
            - /opt/psa/var/modules/letsencrypt/etc/live/_plesk_domain/privkey.pem:/etc/ssl/private/mykey.pem
        networks:
            - data-narrator-network

    story-backend:
        build:
            context: ./story-backend
        ports:
            - "4000:80"
            - "4443:443"
        depends_on:
            - mongo
        volumes:
            - /opt/psa/var/modules/letsencrypt/etc/live/_plesk_domain/fullchain.pem:/etc/ssl/certs/mycert.pem
            - /opt/psa/var/modules/letsencrypt/etc/live/_plesk_domain/privkey.pem:/etc/ssl/private/mykey.pem
        networks:
            - data-narrator-network

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - data-narrator-network

volumes:
    mongo-data:

networks:
    data-narrator-network:
