services:
    data-narrator-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:80'
        volumes:
            - /opt/psa/var/modules/letsencrypt/etc/archive/_plesk_domain/fullchain2.pem:/etc/ssl/certs/mycert.pem
            - /opt/psa/var/modules/letsencrypt/etc/archive/_plesk_domain/privkey2.pem:/etc/ssl/private/mykey.pem
        networks:
            - data-narrator-network

    story-backend:
        build:
            context: ./story-backend
        ports:
            - "4000:80"
            - "4443:443"
        depends_on:
            - mongo
        volumes:
            - /opt/psa/var/modules/letsencrypt/etc/archive/_plesk_domain/fullchain2.pem:/etc/ssl/certs/mycert.pem
            - /opt/psa/var/modules/letsencrypt/etc/archive/_plesk_domain/privkey2.pem:/etc/ssl/private/mykey.pem
        networks:
            - data-narrator-network

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - data-narrator-network

    keycloak:
        image: jboss/keycloak:latest
        ports:
            - "8080:8080"
            - "8443:8443"  # Expose 8443 for potential future SSL testing
        environment:
            - DB_VENDOR=postgres
            - DB_ADDR=keycloak-db
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=keycloakpassword
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=adminpassword
            - PROXY_ADDRESS_FORWARDING=true
        depends_on:
            - keycloak-db
        networks:
            - story-network

    keycloak-db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=keycloakpassword
        volumes:
            - keycloak-data:/var/lib/postgresql/data
        networks:
            - story-network

volumes:
    mongo-data:

networks:
    data-narrator-network:
